export const uniqueAccessList = [
  'obx-view-shedule',
  'obx-view-dashboard',
  'obx-view-geofencing',
  'ho-view-franchise-update',
  'obx-create-vehicle',
  'sales-view-companies',
  'ho-view-franchise-zone-create',
  'ho-view-dashboard',
  'ho-view-franchise-detail',
  'obx-view-zones',
  'obx-view-vehicles',
  'obx-view-zone-site-update',
  'obx-view-zone-site-create',
  'obx-view-franchise-zone-update',
  'obx-view-franchise-zone-create',
  'obx-view-franchise-map',
  'obx-view-schedule',
  'obx-view-runsheets',
  'obx-view-dispatch',
  'obx-view-reports',
  'obx-view-users',
  'obx-view-analytics',
  'obx-view-leaderboard',
  // 'obx-view-devices',
  'obx-view-sites',
  'obx-view-settings',
  'ho-view-franchise-zone-update',
  'sales-view-dashboard',
  'sales-view-company-details',
  'ho-view-franchises',
  'sales-view-locations',
  'sales-view-location-details',
  'ho-view-user',
  'sales-view-deals',
  'sales-view-deal-details',
  // 'obx-view-invoices',
  'obx-view-reports-details',
];

export const obxModuleAccessList = [
  'obx-view-shedule',
  'obx-view-dashboard',
  'obx-view-geofencing',
  'obx-create-vehicle',
  'obx-view-zones',
  'obx-view-zone-update',
  'obx-view-invoices',
  'obx-view-zone-create',
  'obx-view-vehicles',
  'obx-view-zone-site-update',
  'obx-view-zone-site-create',
  'obx-view-zone-update',
  'obx-view-zone-create',
  'obx-view-franchise-map',
  'obx-view-schedule',
  'obx-view-runsheets',
  'obx-view-dispatch',
  'obx-view-dispatch-details',
  'obx-view-dispatch-assign-officer',
  'obx-view-reports',
  'obx-view-users',
  // 'obx-view-analytics',
  // 'obx-view-leaderboard',
  // 'obx-view-devices',
  'obx-view-sites',
  'obx-view-settings',
  'obx-view-attendance',
  'obx-view-reports-details',
  'obx-view-settings-preferences',
  'obx-view-settings-threshold-values',
  'obx-view-settings-break-rules',
  'obx-view-settings-runsheet',
  'obx-view-settings-extra-services-charges',
  'obx-view-settings-visitor-types',
  'obx-view-settings-loader-types',
  'obx-view-settings',
  'obx-view-settings-report-templates',
  'obx-view-settings-system-default',
  'obx-view-payroll',
  'obx-view-create-dispatch',
];

export const obxSupervisorModuleAccessList = [
  'obx-view-shedule',
  // 'obx-view-dashboard',
  'obx-view-geofencing',
  'obx-create-vehicle',
  'obx-view-zones',
  'obx-view-zone-update',
  // 'obx-view-invoices',
  'obx-view-zone-create',
  'obx-view-vehicles',
  'obx-view-zone-site-update',
  'obx-view-zone-site-create',
  'obx-view-zone-update',
  'obx-view-zone-create',
  'obx-view-franchise-map',
  'obx-view-schedule',
  'obx-view-runsheets',
  'obx-view-dispatch',
  'obx-view-dispatch-details',
  'obx-view-dispatch-assign-officer',
  'obx-view-reports',
  'obx-view-users',
  // 'obx-view-analytics',
  // 'obx-view-leaderboard',
  // 'obx-view-devices',
  'obx-view-sites',
  // 'obx-view-settings',
  'obx-view-attendance',
  'obx-view-reports-details',
  // 'obx-view-settings-preferences',
  // 'obx-view-settings-threshold-values',
  // 'obx-view-settings-break-rules',
  // 'obx-view-settings-runsheet',
  // 'obx-view-settings-extra-services-charges',
  // 'obx-view-settings-visitor-types',
  // 'obx-view-settings-loader-types',
  // 'obx-view-settings',
  // 'obx-view-settings-report-templates',
  'obx-view-payroll',
  'sales-view-leads-reviews',
];

export const hoModuleAccessList = [
  'ho-view-franchise-update',
  'ho-view-franchise-zone-create',
  // 'ho-view-dashboard',
  'ho-view-franchise-detail',
  'ho-view-franchise-zone-update',
  'ho-view-franchises',
  'sales-view-dashboard',
  'sales-view-companies',
  'sales-view-company-details',
  'sales-view-locations',
  'sales-view-location-details',
  'sales-view-deals',
  'ho-view-franchise-map',
  'sales-question-edit',
  // 'ho-view-user',
  'ho-view-settings',
  'sales-view-deal-details',
  'sales-view-industry-verticals',
  'sales-view-industry-verticals-details',
  'sales-view-contract-creation',
  'sales-view-users',
  'sales-view-contacts',
  'sales-view-contact-details',
  'obx-view-settings-preferences',
  'obx-view-settings-threshold-values',
  'obx-view-settings-break-rules',
  'obx-view-settings-runsheet',
  'obx-view-settings-extra-services-charges',
  'obx-view-settings',
  'obx-view-settings-report-templates',
  'obx-view-settings-system-default',
  'sales-view-settings',
  'sales-view-scouting',
  'sales-view-contact-details',
  'sales-view-dashboard-details',
  'sales-view-leads-map',

  // Access site details
  'ho-view-sites',
  // 'obx-view-invoices_settings',
  // 'obx-view-invoices',
  'ho-view-schedule', // trying to provide access of create extra job only, to HO
  'sales-view-leads-reviews',
  'sales-update-leads-reviews',
];

export const salesModuleAccessList = [
  'sales-view-dashboard',
  'sales-view-companies',
  'sales-view-company-details',
  'sales-view-locations',
  'sales-view-location-details',
  'sales-view-deals',
  'sales-question-edit',
  'sales-view-deal-details',
  'sales-view-industry-verticals',
  'sales-view-industry-verticals-details',
  'sales-view-contract-creation',
  'sales-view-leads-map',
  // 'sales-view-users',
  'sales-view-contacts',
  'sales-view-settings',
  'sales-view-scouting',
  'sales-view-contact-details',
  'sales-view-dashboard-details',
  'sales-view-leads-reviews',
];

export const hoAgentModuleAccessList = [
  'obx-view-dispatch',
  'obx-view-dispatch-details',
  'obx-view-dispatch-assign-officer',
  'obx-view-dispatch-runsheet',
  'obx-view-create-dispatch',
  'obx-view-assign-officer',
];
